- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/latest.tar.gz

- name: Extraer WordPress
  unarchive:
    src: /tmp/latest.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Cambiar permisos
  file:
    path: /var/www/html/wordpress
    owner: www-data
    group: www-data
    recurse: yes
